class AppLabels {
  static const String OfflineTitle = "You are offline!";
  static const String landingTitle1 = "FLEXIBLE PAYMENT OPTIONS";
  static const String landingTitle2 = "SHOPPING FROM HOME";
  static const String landingTitle3 = "EXPRESS DELIVERY";
  static const String landingSubTitle1 =
      "Lorem Ipsum is simply dummy text of the printing industry.";
  static const String landingSubTitle2 =
      "Lorem Ipsum is simply dummy text of the printing industry.";
  static const String landingSubTitle3 =
      "Lorem Ipsum is simply dummy text of the printing industry.";
}

class AppStrings {
  static const String appName = "GoPotu";
  static const String developBy = "Developed by";
  static const String syscogen = "Syscogen";
  static const String technologyPartner = "Technology Partner";
  static const String teamTechInVein = "TechInVein.com";
  static const String next = "Next";
  static const String getStarted = "GET STARTED";
  static const String hey = "Hey,";
  static const String intro1 = "Quick Grocery, Food & ";
  static const String intro2 = "Shopping Items at your Doorstep ";
  static const String Mobile = "Mobile Number";
  static const String loginNowFirst = "Login Now.";
  static const String ifYou = "If you are new / Create New";
  static const String mobileNumber = "Mobile Number";
  static const String password = "Password";
  static const String forgotPasswordReset = "Forgot Password / Reset";
  static const String loginNow = "Login Now";
  static const String doNotHaveAccount = "Don't have an account ?";
  static const String createNewAccount = " Create New Account";
  static const String registerNow = "Register Now.";
  static const String almostThere = "You are almost there !";
  static const String fullName = "Full Name";
  static const String firstName = "First Name";
  static const String lastName = "Last Name";
  static const String email = "Email";
  static const String confirmPassword = "Confirm Password";
  static const String alreadyHaveAccount = "Already have an account ?";
  static const String login = " Login";
  static const String register = "Register";
  // static const String DoReceivedAnyOtp = "Didn't receive any OTP ?"; //old
  static const String DoReceivedAnyOtp = "Didn't Receive Code?";
  // static const String resendOTP = " Resend OTP"; //old
  static const String resendOTP = "Get a New one"; //old
  static const String verificationCode = "Verification Code";
  static const String pleaseTypeTheVerification =
      "Please type the verification code sent to \nyour mobile number.";
  static const String wehavesentverificationcode =
      "We have sent you a 4 digit code.Please enter \nhere to verify your Number.";
  static const String verifyAndContinue = "Verify and Continue";
  static const String chooseShoppingAddress = "Choose Shopping Address";
  static const String searchByRestaurantsName = "Search by restaurants name";
  static const String selectedShoppingCategory = "Selected Shopping Category";
  static const String change = "Change";
  static const String topStoreForYou = "Top stores for you";
  static const String whatAreYouLookingFor = "What Are You Looking For";
  static const String whatdoyouwant = "What Do You Want";
  static const String specialofferZone = "Special Offer Zone";
  static const String exploreOurStore = "Explore Our Store";
  static const String newProducts = "New Products";
  static const String viewAll = "See All";
  static const String shopCategory = "Shop Category";
  static const String chooseACategory =
      "Choose a category to continue shopping";
  static const String myOrders = "My Orders";
  static const String filter = "Filter";
  static const String manageYourOrder = "Manage your order";
  static const String orderStatus = "Order Status";
  static const String expectedDelivery = "Expected delivery";
  static const String orderId = "Order Id";
  static const String orderTotal = "Order Total";
  static const String contactUs = "Contact us";
  static const String viewDetails = "View Details";
  static const String orderDetails = "Order Details";
  static const String paymentMode = "Payment Mode";
  static const String paymentStatus = "Payment Status";
  static const String billingDetails = "Billing Details";
  static const String OrderItems = "Order items";
  static const String DeliveryAddress = "Delivery Address";
  static const String RefundRequest = "Return/Replace Request";
  static const String ReturnRequest = "Return Request";
  static const String DownloadInvoice = "Download Invoice";
  static const String ClickOnDownload = "Click on download & get invoice";
  static const String Download = "Download";
  static const String CancelOrder = "Cancel Order";
  static const String CallToStore = "Admin Call";
  static const String MRPTotal = "MRP Total";
  static const String DeliveryFee = "Delivery fee";
  static const String CouponDiscount = "Coupon Discount";
  static const String AvailableStores = "Available Stores";
  static const String AllCategories = "All Category";
  static const String AllOffers = "All Offers";
  static const String AllProductOffer = "All Products";
  static const String StoreDetails = "Store Details";
  static const String ShoppingCategory = "Shopping Category";
  static const String MyAccount = "My Account";
  static const String EditAccount = "Edit Account";
  static const String UpdateDetails = "Update Details";
  static const String MyBasket = "View Cart";
  static const String ChangeOrAddAddress = "Change or Add address";
  static const String ChangeLocation = "Change Location";
  static const String PaymentDetails = "Payment Details";
  static const String VIEW = "VIEW";
  static const String Continue = "Continue";
  static const String PromoOffers = "Promo Offers";
  static const String ContinueShopping = "Continue Shopping";
  static const String ProductDetails = "Product Details";
  static const String ProductList = "Product List";
  static const String AboutUs = "About Us";
  static const String NeedHelp = "Need Help";
  static const String RequestNow = "Request Now";
  static const String RateUs = "Rate Us";
  static const String Submit = "Submit";
  static const String Notifications = "Notifications";
  static const String AddAddress = "Add Address";
  static const String EditAddress = "Edit Address";
  static const String SaveAddress = "Save Address";
  static const String PlaceOrder = "Place Order";
  static const String changePassword = "Change Password";
  static const String oldPassword = "Old Password";
  static const String newPassword = "New Password";
  static const String continueWithOutLogin = "Continue Without Login";
  static const String gst = "GST";
  static const String OfflineMessage = "Please Check your network status.";
  static const String Name = "Name";
}
